### ISSUE TITLE
Error when enabling certificate and rendering templates

### ISSUE THREAD

**Issue by ErwinSteffens** [SchwarzIT/node-red-chart#301] opened 2023-12-09 16:13 UTC
### What happened?

When enabling certificate an error happens while rendering the templates:

```
Error: INSTALLATION FAILED: template: node-red/templates/certificates.yaml:8:24: executing "node-red/templates/certificates.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

### How can we reproduce this?

```
ingress:
  enabled: true
  tls: 
    - secretName: node-red
      hosts:
      - node-red.com
      certificate:
        enabled: true
        issuerRef:
          kind: ClusterIssuer
          name: letsencrypt
```

### Helm Chart version

```bash
0.28.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

None

**Comment by dirien** [comment] 2023-12-15 09:54
Hey @ErwinSteffens,

thanks for the issue and PR. 

I have trouble to understand what the issue is your PR is fixing?

**Comment by dirien** [comment] 2023-12-18 12:38
@ErwinSteffens, nice find! 👍 Thanks for the PR, it's merged!

**Closed** 2023-12-18 12:37 UTC
Labels: bug
